FROM node:22-alpine AS builder

WORKDIR /app

ARG PUBLIC_RECIPIENT_NAME
ARG PUBLIC_INITIALS
ARG PUBLIC_PAGE_TITLE
ARG PUBLIC_CELEBRATION_MESSAGE
ARG PUBLIC_AUTOMATON_TITLE

ENV PUBLIC_RECIPIENT_NAME=$PUBLIC_RECIPIENT_NAME
ENV PUBLIC_INITIALS=$PUBLIC_INITIALS
ENV PUBLIC_PAGE_TITLE=$PUBLIC_PAGE_TITLE
ENV PUBLIC_CELEBRATION_MESSAGE=$PUBLIC_CELEBRATION_MESSAGE
ENV PUBLIC_AUTOMATON_TITLE=$PUBLIC_AUTOMATON_TITLE

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
